### ISSUE TITLE
null byte should be stripped?

### ISSUE THREAD

**Issue by yukinying** [yahoo/xss-filters#10]
Null byte is problematic in the HTML5 specification. I think it has no benefit having null byte allowed in any filtered output. Thoughts?

**Comment by adon-at-work** [comment]
Given 
```html
<a href={{{uriInUnQuotedAttr url}}} id=link1>hello</a>
```
There's a possibility that url is **empty**, and if there's no null char injection, the rendered output is:
```html
<a href= id="link1">hello</a>
```
The problem is now obvious, ` id=link1` becomes the attribute value of href, which is likely contradictory to the developer's belief.

So, the null char injection there is to avoid such a state-changing consequence, which is the ultimate goal of our xss-filters. No problem? I'll close this "issue".

**Comment by yukinying** [comment]
I was referring to null byte "\0", not empty string ("").

**Comment by adon-at-work** [comment]
I was illustrating the importance of allowing null char with an example using uriInUnquotedAttr(). So this answers your question, we'd not strip null chars.

> if the input is "\0" for uriInUnQuotedAttr, should the output be "" (empty) or "\0" or "\uFFFD"
- the output is now `\0`, therefore untouched. 
- changing it to empty is incorrect, because that would affect how the browser and context-parser parses subsequent content (and therefore the corresponding filter), as shown in the example given. To ease your understanding, please ask yourself what's the context of {{id}} when `url` is empty or non-emptied by `\0` in `<a href={{url}} id={{id}}>hello</a>`.
- based on the minimal encoding principle, the responsibility to turn `\0` to `\uFFFD` is the responsibility of browser.

I think throughout the conversation here, you just said "Null byte is problematic in the HTML5 specification". But can you please clarify how problematic and why problematic?

**Comment by yukinying** [comment]
My proposition is that seeing \0 in input always hinting us this is an attack attempt. It is nice seeing you explaining it does not affect the filter logic and I think I am good to close it :)
